CREATE DATABASE IF NOT EXISTS grd
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE grd;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(150) NOT NULL,
  email VARCHAR(180) NOT NULL,
  senha_hash VARCHAR(255) NOT NULL,
  role ENUM('admin', 'viewer') NOT NULL DEFAULT 'viewer',
  ativo TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_usuarios_email (email)
);

CREATE TABLE IF NOT EXISTS registros (
  id INT NOT NULL AUTO_INCREMENT,
  data_reuniao DATE NOT NULL,
  dia_reuniao VARCHAR(30) NOT NULL,
  data_analisada DATE NOT NULL,
  dia_analisado VARCHAR(30) NOT NULL,
  uo VARCHAR(20) NOT NULL,
  processo VARCHAR(120) NOT NULL,
  participante VARCHAR(150) NOT NULL,
  funcao VARCHAR(80) NOT NULL,
  us_programada_wm DECIMAL(10,2) NULL,
  us_realizada_wm DECIMAL(10,2) NULL,
  desvio_wm DECIMAL(10,2) NULL,
  us_programada_lt DECIMAL(10,2) NULL,
  us_realizada_lt DECIMAL(10,2) NULL,
  desvio_lt DECIMAL(10,2) NULL,
  complemento_lancado VARCHAR(255) NULL,
  mf_us_dia DECIMAL(10,2) NULL,
  mt_us_dia DECIMAL(10,2) NULL,
  equipes_d_moto INT NULL,
  equipes_d_equipe INT NULL,
  equipe_orcada_d1 INT NULL,
  equipe_total_d1 INT NULL,
  equipe_programada_d1 INT NULL,
  equipe_efetiva_d1 INT NULL,
  plataforma_qtd_eqp INT NULL,
  plataforma_hora_liberada VARCHAR(50) NULL,
  almoxarifado_qtd_eqp INT NULL,
  almoxarifado_hora_liberacao VARCHAR(50) NULL,
  absenteismo_atestado_qtd INT NULL,
  previsao_retorno_atestado_d1 VARCHAR(100) NULL,
  absenteismo_falta_qtd INT NULL,
  motivo_falta_d1 VARCHAR(255) NULL,
  oficina_qtd_d1 INT NULL,
  oficina_hora_liberacao_d1 VARCHAR(50) NULL,
  motivo_perda_1 VARCHAR(255) NULL,
  motivo_perda_2 VARCHAR(255) NULL,
  motivo_perda_3 VARCHAR(255) NULL,
  motivo_perda_4 VARCHAR(255) NULL,
  motivo_perda_5 VARCHAR(255) NULL,
  equipe_programada_hoje INT NULL,
  equipe_prevista_hoje INT NULL,
  atestado_qtd_hoje INT NULL,
  atestado_previsao_retorno_hoje VARCHAR(100) NULL,
  falta_hoje INT NULL,
  motivo_falta_hoje VARCHAR(255) NULL,
  oficina_qtd_hoje INT NULL,
  oficina_previsao_liberacao_hoje VARCHAR(100) NULL,
  treinamento_qtd_hoje INT NULL,
  treinamento_finalidade_hoje VARCHAR(255) NULL,
  foco_prioridade_1 VARCHAR(255) NULL,
  foco_prioridade_2 VARCHAR(255) NULL,
  foco_prioridade_3 VARCHAR(255) NULL,
  foco_prioridade_4 VARCHAR(255) NULL,
  foco_prioridade_5 VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
